<a href="https://colab.research.google.com/github/msamee007/ML-Projects/blob/main/ML_Project_Diabetes_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #Numpy arrays
import pandas as pd #creating data frames in a structured table
from sklearn.preprocessing import StandardScaler #used to stardize data into a normal range
from sklearn.model_selection import train_test_split#used to split data into training and testing
from sklearn import svm #used to import SUpportVectorMachine algorithm
from sklearn.metrics import accuracy_score#used to find the accuracy of the final test

Data collection and Analysis
PIMA diabetes dataset

In [ ]:
#loading the dataset to a pandas file
diabetes_dataset = pd.read_csv('/content/diabetes.csv')

In [ ]:
#the head function helps to bring the first 5 rows of the dataset
diabetes_dataset.head()

,Unnamed: 0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,2,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0
2,3,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,4,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,5,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0

In [ ]:
#number of rows and column, shape helps you to know the dimension of the data
diabetes_dataset.shape

(769, 10)

In [ ]:
# Statistical measures of the data
diabetes_dataset.describe()

,Unnamed: 0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,769.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,385.000000,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,222.135469,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,193.000000,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,385.000000,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,577.000000,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,769.000000,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0.0    500
1.0    268
Name: count, dtype: int64

0----> Non diabetic

1----> Diabetic

In [ ]:
diabetes_dataset.groupby('Outcome').mean()

,Unnamed: 0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,,
0.0,391.834000,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1.0,370.817164,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [ ]:
#seperating the data and labels
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

Data Standardization

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:
standardized_data = scaler.transform(X)

In [ ]:
X= standardized_data
Y= diabetes_dataset['Outcome']

Train test Split

In [ ]:
nan_indices = Y.isna()
X_cleaned = X[~nan_indices]
Y_cleaned = Y[~nan_indices]

X_train, X_test, Y_train, Y_test = train_test_split(X_cleaned, Y_cleaned, test_size = 0.2, stratify=Y_cleaned, random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(769, 9) (614, 9) (154, 9)

Training the model

In [ ]:
classifier=svm.SVC(kernel='linear')

In [ ]:
#training the support vector machine classifier
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

MODEL EVALUATION

Accuracy Score

In [ ]:
#accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print(training_data_accuracy)

0.7662337662337663

In [ ]:
#accuracy score on the test data
#accuracy score on the training data
X_train_prediction = classifier.predict(X_test)
training_data_accuracy = accuracy_score(X_train_prediction, Y_test)

In [ ]:
print(training_data_accuracy)

0.7662337662337663

Making a Predictive System

In [ ]:
input_data=(1,5,166,72,19,175,25.8,0.587,51)
#change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
#reshpe the array for predicting one instance
std_data = scaler.transform(input_data_reshaped)
prediction = classifier.predict(std_data)
print(prediction)

[1.]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(